CREATE TYPE "public"."answer_status" AS ENUM('accepted', 'disputed', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."game_status" AS ENUM('lobby', 'playing', 'reviewing', 'finished');--> statement-breakpoint
CREATE TABLE "naming-things_answer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_answer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" integer NOT NULL,
	"playerId" integer NOT NULL,
	"text" varchar(256) NOT NULL,
	"normalizedText" varchar(256) NOT NULL,
	"status" "answer_status" DEFAULT 'accepted' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "naming-things_dispute_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_dispute_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"answerId" integer NOT NULL,
	"voterPlayerId" integer NOT NULL,
	"accept" boolean NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "naming-things_game_player" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_game_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" integer NOT NULL,
	"playerId" integer NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"joinedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "naming-things_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(6) NOT NULL,
	"hostPlayerId" integer NOT NULL,
	"status" "game_status" DEFAULT 'lobby' NOT NULL,
	"category" varchar(256),
	"timerSeconds" integer DEFAULT 60 NOT NULL,
	"startedAt" timestamp with time zone,
	"endedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "naming-things_game_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "naming-things_player" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionToken" varchar(256) NOT NULL,
	"displayName" varchar(100) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "naming-things_player_sessionToken_unique" UNIQUE("sessionToken")
);
--> statement-breakpoint
CREATE INDEX "answer_game_idx" ON "naming-things_answer" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "answer_player_idx" ON "naming-things_answer" USING btree ("gameId","playerId");--> statement-breakpoint
CREATE UNIQUE INDEX "dispute_vote_unique_idx" ON "naming-things_dispute_vote" USING btree ("answerId","voterPlayerId");--> statement-breakpoint
CREATE INDEX "dispute_vote_answer_idx" ON "naming-things_dispute_vote" USING btree ("answerId");--> statement-breakpoint
CREATE UNIQUE INDEX "game_player_idx" ON "naming-things_game_player" USING btree ("gameId","playerId");--> statement-breakpoint
CREATE INDEX "game_player_game_idx" ON "naming-things_game_player" USING btree ("gameId");--> statement-breakpoint
CREATE UNIQUE INDEX "code_idx" ON "naming-things_game" USING btree ("code");--> statement-breakpoint
CREATE UNIQUE INDEX "session_token_idx" ON "naming-things_player" USING btree ("sessionToken");