CREATE TYPE "public"."category_fit_label" AS ENUM('valid', 'invalid', 'ambiguous');--> statement-breakpoint
CREATE TABLE "naming-things_answer_verification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_answer_verification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"answerId" integer NOT NULL,
	"gameId" integer NOT NULL,
	"label" "category_fit_label" NOT NULL,
	"confidence" integer,
	"reason" varchar(512),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "naming-things_game" ADD COLUMN "autoClassificationEnabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "answer_verification_answer_idx" ON "naming-things_answer_verification" USING btree ("answerId");--> statement-breakpoint
CREATE INDEX "answer_verification_game_idx" ON "naming-things_answer_verification" USING btree ("gameId");