CREATE TYPE "public"."solo_run_status" AS ENUM('playing', 'finished', 'abandoned');--> statement-breakpoint
CREATE TABLE "naming-things_category_alias" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_category_alias_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"alias" varchar(256) NOT NULL,
	"aliasSlug" varchar(256) NOT NULL,
	"canonicalName" varchar(256) NOT NULL,
	"canonicalSlug" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "naming-things_solo_run_answer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_solo_run_answer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"runId" integer NOT NULL,
	"playerId" integer NOT NULL,
	"text" varchar(256) NOT NULL,
	"normalizedText" varchar(256) NOT NULL,
	"label" "category_fit_label",
	"confidence" real,
	"reason" varchar(512),
	"isDuplicate" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "naming-things_solo_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_solo_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playerId" integer NOT NULL,
	"inputCategory" varchar(256) NOT NULL,
	"categoryDisplayName" varchar(256) NOT NULL,
	"categorySlug" varchar(256) NOT NULL,
	"timerSeconds" integer NOT NULL,
	"status" "solo_run_status" DEFAULT 'playing' NOT NULL,
	"startedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"endedAt" timestamp with time zone,
	"durationMs" integer,
	"score" integer DEFAULT 0 NOT NULL,
	"validCount" integer DEFAULT 0 NOT NULL,
	"invalidCount" integer DEFAULT 0 NOT NULL,
	"ambiguousCount" integer DEFAULT 0 NOT NULL,
	"judgeModel" varchar(256),
	"judgeVersion" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "category_alias_slug_idx" ON "naming-things_category_alias" USING btree ("aliasSlug");--> statement-breakpoint
CREATE INDEX "solo_answer_run_normalized_idx" ON "naming-things_solo_run_answer" USING btree ("runId","normalizedText");--> statement-breakpoint
CREATE INDEX "solo_run_leaderboard_idx" ON "naming-things_solo_run" USING btree ("categorySlug","timerSeconds");--> statement-breakpoint
CREATE INDEX "solo_run_player_bucket_idx" ON "naming-things_solo_run" USING btree ("playerId","categorySlug","timerSeconds");