CREATE TABLE "naming-things_solo_run_judgment_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_solo_run_judgment_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"runId" integer NOT NULL,
	"judgeModel" varchar(256),
	"judgeVersion" varchar(256),
	"score" integer NOT NULL,
	"validCount" integer NOT NULL,
	"invalidCount" integer NOT NULL,
	"ambiguousCount" integer NOT NULL,
	"answersSnapshot" jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "naming-things_solo_run_judgment_history" ADD CONSTRAINT "naming-things_solo_run_judgment_history_runId_naming-things_solo_run_id_fk" FOREIGN KEY ("runId") REFERENCES "public"."naming-things_solo_run"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "solo_run_judgment_history_run_idx" ON "naming-things_solo_run_judgment_history" USING btree ("runId");