CREATE TABLE "naming-things_category_evidence_packet_slug_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_category_evidence_packet_slug_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categorySlug" varchar(256) NOT NULL,
	"categoryEvidencePacketId" varchar(64) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "naming-things_category_evidence_packet_slug_assignment" ADD CONSTRAINT "naming-things_category_evidence_packet_slug_assignment_categoryEvidencePacketId_naming-things_category_evidence_packet_id_fk" FOREIGN KEY ("categoryEvidencePacketId") REFERENCES "public"."naming-things_category_evidence_packet"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "category_evidence_packet_slug_assignment_slug_idx" ON "naming-things_category_evidence_packet_slug_assignment" USING btree ("categorySlug");--> statement-breakpoint
CREATE INDEX "category_evidence_packet_slug_assignment_packet_idx" ON "naming-things_category_evidence_packet_slug_assignment" USING btree ("categoryEvidencePacketId");