CREATE TABLE "naming-things_solo_category_answer_judgment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "naming-things_solo_category_answer_judgment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"categorySlug" varchar(256) NOT NULL,
	"categoryDisplayName" varchar(256) NOT NULL,
	"normalizedText" varchar(256) NOT NULL,
	"label" "category_fit_label" NOT NULL,
	"confidence" real,
	"reason" varchar(512),
	"judgeModel" varchar(256),
	"judgeVersion" varchar(256) NOT NULL,
	"categoryEvidencePacketId" varchar(64),
	"judgmentContextKey" varchar(64) NOT NULL,
	"sourceRunId" integer,
	"sourceAnswerId" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "naming-things_solo_category_answer_judgment" ADD CONSTRAINT "naming-things_solo_category_answer_judgment_categoryEvidencePacketId_naming-things_category_evidence_packet_id_fk" FOREIGN KEY ("categoryEvidencePacketId") REFERENCES "public"."naming-things_category_evidence_packet"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "naming-things_solo_category_answer_judgment" ADD CONSTRAINT "naming-things_solo_category_answer_judgment_sourceRunId_naming-things_solo_run_id_fk" FOREIGN KEY ("sourceRunId") REFERENCES "public"."naming-things_solo_run"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "naming-things_solo_category_answer_judgment" ADD CONSTRAINT "naming-things_solo_category_answer_judgment_sourceAnswerId_naming-things_solo_run_answer_id_fk" FOREIGN KEY ("sourceAnswerId") REFERENCES "public"."naming-things_solo_run_answer"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "solo_category_answer_judgment_unique_idx" ON "naming-things_solo_category_answer_judgment" USING btree ("categorySlug","normalizedText","judgmentContextKey");--> statement-breakpoint
CREATE INDEX "solo_category_answer_judgment_category_idx" ON "naming-things_solo_category_answer_judgment" USING btree ("categorySlug");--> statement-breakpoint
CREATE INDEX "solo_category_answer_judgment_answer_idx" ON "naming-things_solo_category_answer_judgment" USING btree ("normalizedText");--> statement-breakpoint
CREATE INDEX "solo_category_answer_judgment_packet_idx" ON "naming-things_solo_category_answer_judgment" USING btree ("categoryEvidencePacketId");