export const TOPIC_SUGGESTIONS = [
  "types of cheese",
  "harry potter characters",
  "cartoon characters",
  "pizza toppings",
  "dog breeds",
  "board games",
  "periodic table elements",
  "famous landmarks",
  "ice cream flavors",
  "marvel characters",
  "breakfast foods",
  "musical instruments",
  "snack foods",
  "vegetables",
  "olympic sports",
  "nfl teams",
  "animated movies",
  "birds",
  "cocktails",
  "u.s. presidents",
  "candy bars",
  "world capitals",
  "tv shows",
  "card games",
  "desserts",
  "mythical creatures",
  "pasta shapes",
  "nba teams",
  "body parts",
  "types of fish",
  "greek gods",
  "disney movies",
  "fast food chains",
  "currencies",
  "yoga poses",
  "video game characters",
  "taylor swift songs",
  "countries in africa",
  "sandwich types",
  "corporate logos",
  "shakespeare plays",
  "national parks",
  "children's books",
  "pokémon",
  "fairy tale characters",
  "star wars characters",
  "rock bands",
  "fruits",
  "horror movies",
  "game of thrones characters",
  "animals at a zoo",
  "comedians",
  "simpsons characters",
  "toys",
  "christmas songs",
  "action movies",
  "rom-coms",
  "countries in asia",
  "premier league clubs",
  "car brands",
  "herbs and spices",
  "rappers",
  "dances",
  "rides at a theme park",
  "apps",
  "countries in europe",
  "baby names",
  "world flags",
  "u.s. states",
  "countries of the world",
  "90s tv shows",
  "languages",
  "mlb teams",
  "insects",
  "flowers",
  "musicals",
  "cereals",
  "reptiles",
  "the office characters",
  "farm animals",
  "oscar best picture winners",
  "ocean creatures",
  "cat breeds",
  "super smash bros. characters",
  "nhl teams",
  "kitchen utensils",
  "dinosaurs",
  "comedies",
  "superheroes",
  "candy",
  "video games",
];
